export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const VERIFY_TITLE_REF = 'verifyTitleRef'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const UPDATE_USER = 'updateUser'
